names = [
    "Alex Morgan",
    "Ethan Williams",
    "Johnny Sins",
    "Johnny Sins",
    "Johnny Sins",
    "Johnny Sins",
    "Johnny Sins",
    "Johnny Sins",
    "Johnny Sins",
    "Ricky Johnson",
    "J. Mac",
    "Sweetie Fox",
    "Bonnie Blue",
    "Dan TDM",
    "Jacksepticeye",
    "Pewdiepie",
    "Obama Barrack Jimmyson"
    "Daniel Chen",
    "Michael Anderson",
    "James Patel",
    "Noah Thompson",
    "Ryan Johnson",
    "Oliver Smith",
    "Liam Carter",
    "Benjamin Lee",
    "William Davis",
    "Lucas Wilson",
    "Henry Brown",
    "Jack Taylor",
    "Samuel Martin",
    "Nathan Walker",
    "David Kim",
    "Matthew Clark",
    "Andrew Garcia",
    "Christopher Moore",
    "Alexander Singh",
    "Thomas Nguyen",
    "Jacob Wilson",
    "Robert Martinez",
    "Adam Johnson",
    "Kevin Zhang",
    "Jason Miller",
    "Brian Anderson",
    "Eric Robinson",
    "Dylan Thompson",
    "Andrew Ate",
    "Oliver Black",
    "Blaine Brown",
    "Jeremy Brown",
    "Aniki's Long Johnson",
    "Noto Puffs",
    "Sofee Dewa Alexander The Goat Sofian Affendi",
    "Alper The 3rd Dindar",
    "John Cena",
    "Latrell Waitoa",
    "Tutku Pincer",
    "Jeremy Bing"
]


emails = [
    "alex.morgan.dev@gmail.com",
    "ethan.williams.cs@gmail.com",
    "daniel.chen.engineer@gmail.com",
    "michael.anderson.dev@gmail.com",
    "j.patel.software@gmail.com",
    "noah.builds.apps@gmail.com",
    "ryan.johnson.tech@gmail.com",
    "oliver.smith.codes@gmail.com",
    "liam.carter.engineering@gmail.com",
    "ben.lee.software@gmail.com",
    "william.davis.dev@gmail.com",
    "lucas.wilson.tech@gmail.com",
    "henry.brown.cs@gmail.com",
    "jack.taylor.engineer@gmail.com",
    "samuel.martin.dev@gmail.com",
    "nathan.walker.codes@gmail.com",
    "david.kim.software@gmail.com",
    "matthew.clark.engineering@gmail.com",
    "andrew.garcia.dev@gmail.com",
    "chris.moore.tech@gmail.com",
    "alex.singh.cs@gmail.com",
    "thomas.nguyen.dev@gmail.com",
    "jacob.wilson.engineer@gmail.com",
    "robert.martinez.codes@gmail.com",
    "adam.johnson.software@gmail.com",
    "kevin.zhang.dev@gmail.com",
    "jason.miller.engineering@gmail.com",
    "brian.anderson.cs@gmail.com",
    "eric.robinson.tech@gmail.com",
    "dylan.thompson.dev@gmail.com"
]


locations = [
    "San Francisco, CA",
    "Seattle, WA",
    "Austin, TX",
    "New York, NY",
    "Boston, MA",
    "Toronto, Canada",
    "London, UK",
    "Berlin, Germany",
    "Remote",
    "Los Angeles, CA",
    "Chicago, IL",
    "Vancouver, Canada",
    "Sydney, Australia",
    "Singapore",
    "Tokyo, Japan",
    "Denver, CO",
    "Portland, OR",
    "Miami, FL",
    "Atlanta, GA",
    "Dallas, TX",
    "Silicon Valley",
    "Cloud Infrastructure Region 1",
    "Remote Global Headquarters",
    "Distributed Engineering Hub",
    "The Internet",
    "Metaverse Development Center",
    "Enterprise Innovation Campus",
    "Open Source Community",
    "AI Research District",
    "Future Technology Valley",
    "Beijin, NZ",
    "19 sunvale cresent, NZ"
]


institutions = [
    "Stanford University",
    "Massachusetts Institute of Technology",
    "University of California Berkeley",
    "University of Washington",
    "Georgia Institute of Technology",
    "Carnegie Mellon University",
    "University of Toronto",
    "University of Waterloo",
    "University of Oxford",
    "University of Cambridge",
    "New York University",
    "University of Texas at Austin",
    "Purdue University",
    "Arizona State University",
    "Northeastern University",
    "University of Illinois Urbana-Champaign",
    "Open Source University",
    "Institute of Advanced Software Engineering",
    "Global Computing Academy",
    "School of Digital Innovation",
    "Enterprise Technology Institute",
    "Department of Applied Algorithms",
    "Future Systems University",
    "Cloud Engineering College",
    "AI Research Institute",
    "Modern Computing Academy",
    "Distributed Systems University",
    "Software Architecture Institute",
    "Next Generation Technology School",
    "The University of Production Readiness",
    "Roblox Dev School",
    "Lytton High School",
    "University of Auckland",
    "University of Otago"
]


degrees = [
    "Bachelor of Computer Science",
    "Bachelor of Software Engineering",
    "Bachelor of Computer Engineering",
    "Bachelor of Information Technology",
    "Master of Computer Science",
    "Master of Artificial Intelligence",
    "Master of Software Systems",
    "Bachelor of Data Science",
    "Bachelor of Cybersecurity",
    "Bachelor of Applied Computing",
    "Computer Science and Mathematics",
    "Software Development Engineering",
    "Artificial Intelligence Engineering",
    "Cloud Computing Systems",
    "Distributed Systems Engineering",
    "Machine Learning and Data Engineering",
    "Human Computer Interaction",
    "Computational Science",
    "Advanced Software Architecture",
    "Enterprise Application Engineering",
    "Modern Application Development",
    "Autonomous Systems Engineering",
    "Full Stack Development",
    "Digital Transformation Engineering",
    "Next Generation Computing",
    "Scalable Systems Engineering",
    "Blockchain Technology",
    "Data Infrastructure Engineering",
    "Software Innovation",
    "Computer Science",
    "Bachelor of Roblox",
    "Masters of Wisdom"
]


gpas = [
    "4.0/4.0",
    "3.9/4.0",
    "3.8/4.0",
    "3.7/4.0",
    "3.6/4.0",
    "3.5/4.0",
    "4.2/4.0 (weighted)",
    "99.8% average",
    "First Class Honours",
    "Distinction",
    "3.95/4.0",
    "4.0/4.0 (top 1%)",
    "3.85/4.0",
    "3.75/4.0",
    "3.65/4.0",
    "4.0/4.0 (production ready)",
    "3.99/4.0",
    "Exceeded grading infrastructure limits",
    "Maximum possible score",
    "Near-perfect academic performance",
    "4.1/4.0 (extra credit)",
    "3.92/4.0",
    "Dean's List",
    "Academic Excellence Award",
    "Top percentile performance",
    "4.0/4.0 with optimized studying pipeline",
    "3.88/4.0",
    "3.76/4.0",
    "4.0/4.0",
    "Above expected benchmarks",
    "Top of shapes and colours class (child prodigy)",
    "1/1"
]


awards = [
    "Dean's List",
    "Academic Excellence Award",
    "Outstanding Software Engineering Award",
    "Hackathon Winner",
    "Best Capstone Project",
    "Open Source Contributor Award",
    "Research Excellence Award",
    "Innovation Scholarship",
    "Technology Leadership Award",
    "Software Architecture Recognition",
    "AI Research Fellowship",
    "Cloud Engineering Award",
    "Student Developer Award",
    "Community Impact Award",
    "Engineering Excellence Award",
    "Future Technology Award",
    "Best Use of Modern Frameworks",
    "Outstanding Problem Solving Award",
    "Global Coding Competition Finalist",
    "Top Developer Recognition",
    "Most Improved Developer Velocity",
    "Enterprise Innovation Award",
    "Scalable Systems Achievement Award",
    "Digital Transformation Award",
    "Best Automation Solution",
    "Production Reliability Award",
    "Zero Downtime Achievement",
    "AI Integration Award",
    "Distinguished Engineering Potential Award",
    "Principal Engineer Preparation Certificate",
    "Most Likely To, P.S.Y get these nuts on your chin"
]


coursework = [
    "Data Structures and Algorithms",
    "Operating Systems",
    "Database Systems",
    "Computer Networks",
    "Software Engineering",
    "Machine Learning",
    "Artificial Intelligence",
    "Distributed Systems",
    "Cloud Computing",
    "Computer Architecture",
    "Information Retrieval",
    "Natural Language Processing",
    "Cybersecurity",
    "Human Computer Interaction",
    "Web Development",
    "Mobile Application Development",
    "Compiler Design",
    "Parallel Computing",
    "Data Mining",
    "Bitcoin Mining",
    "Big Data Engineering",
    "Advanced Databases",
    "Software Testing",
    "Systems Programming",
    "Algorithms and Optimization",
    "Blockchain Systems",
    "Scalable Infrastructure",
    "Enterprise Architecture",
    "Modern Application Frameworks",
    "AI Product Engineering",
    "Production Engineering",
    "Straight Piping"
]

skills = [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "SQL",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Machine Learning",
    "Data Engineering",
    "System Design",
    "API Development",
    "Backend Development",
    "Frontend Development",
    "Cloud Architecture",
    "Database Optimization",
    "Distributed Systems",
    "CI/CD",
    "Testing Automation",
    "Software Architecture",
    "Performance Optimization",
    "DevOps",
    "Microservices",
    "AI Integration",
    "Problem Solving",
    "AI fruit videos",
    "Tik Tok",
    "Watching reels",
    "Consuming",
    "Gooning",
    "Japanese",
    "English"
]


technologies = [
    "React",
    "Next.js",
    "Vue",
    "Angular",
    "Express",
    "FastAPI",
    "Django",
    "Spring Boot",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "MySQL",
    "Docker",
    "Kubernetes",
    "AWS",
    "Google Cloud Platform",
    "Azure",
    "Terraform",
    "GitHub Actions",
    "GraphQL",
    "REST APIs",
    "Kafka",
    "TensorFlow",
    "PyTorch",
    "OpenAI API",
    "Linux",
    "Nginx",
    "RabbitMQ",
    "Firebase",
    "Cloudflare",
    "ChatGPT"
]


companies = [
    "Google",
    "Microsoft",
    "Amazon Web Services",
    "Meta Platforms",
    "OpenAI",
    "Netflix",
    "Stripe",
    "Datadog",
    "Cloudflare",
    "Vercel",
    "Byte Systems",
    "Nova Technologies",
    "Quantum Software Labs",
    "FutureStack",
    "NextGen Solutions",
    "Enterprise Cloud Systems",
    "Digital Frontier Labs",
    "Modern Applications Inc.",
    "Scalable Systems Corp",
    "The Software Factory",
    "AI Infrastructure Group",
    "Distributed Computing Labs",
    "Global Engineering Partners",
    "Cloud Native Solutions",
    "The Algorithm Company",
    "Production Ready Inc.",
    "Infinite Loop Technologies",
    "Stack Overflow Survivors",
    "Framework Industries",
    "Definitely Not A Startup",
]


job_titles = [
    "Software Engineer",
    "Backend Engineer",
    "Frontend Engineer",
    "Full Stack Engineer",
    "Machine Learning Engineer",
    "Cloud Engineer",
    "DevOps Engineer",
    "Platform Engineer",
    "Data Engineer",
    "Systems Engineer",
    "Software Development Intern",
    "Junior Software Engineer",
    "Application Engineer",
    "Infrastructure Engineer",
    "AI Engineer",
    "Distributed Systems Engineer",
    "Solutions Engineer",
    "Technical Software Engineer",
    "Engineering Intern",
    "Research Engineer",
    "Software Architecture Intern",
    "Cloud Platform Specialist",
    "Automation Engineer",
    "API Integration Engineer",
    "Database Engineer",
    "Performance Engineering Specialist",
    "Modernization Engineer",
    "Digital Transformation Engineer",
    "Principal Framework Engineer",
    "Senior Code Optimization Specialist"
]


job_locations = [
    "San Francisco Office",
    "Seattle Headquarters",
    "Remote",
    "New York Engineering Center",
    "London Development Office",
    "Toronto Innovation Hub",
    "Austin Technology Campus",
    "Berlin Engineering Office",
    "Global Remote Team",
    "Cloud Infrastructure Division",
    "AI Research Department",
    "Platform Engineering Group",
    "Distributed Systems Team",
    "Enterprise Solutions Department",
    "Product Engineering Team",
    "Open Source Division",
    "Developer Experience Team",
    "Data Platform Department",
    "The Cloud",
    "Virtual Headquarters",
    "The Main Branch",
    "Production Environment",
    "Remote (Worldwide)",
    "Innovation Lab",
    "Future Technology Center",
    "Algorithm Division",
    "Software Excellence Department",
    "Engineering Operations",
    "Application Platform Team",
    "Digital Systems Group"
]


dates = [
    "Jan 2021 - Jun 2021",
    "Feb 2021 - Aug 2021",
    "Mar 2021 - Dec 2021",
    "May 2021 - Nov 2021",
    "Jan 2022 - Jul 2022",
    "Apr 2022 - Sep 2022",
    "Jun 2022 - Dec 2022",
    "Aug 2022 - Present",
    "Jan 2023 - May 2023",
    "Feb 2023 - Aug 2023",
    "Mar 2023 - Present",
    "May 2023 - Oct 2023",
    "Jun 2023 - Dec 2023",
    "Sep 2023 - Present",
    "Jan 2024 - Apr 2024",
    "Feb 2024 - Jul 2024",
    "Mar 2024 - Sep 2024",
    "May 2024 - Present",
    "Jun 2024 - Dec 2024",
    "Aug 2024 - Present",
    "Jan 2025 - Present",
    "Feb 2025 - Jun 2025",
    "Mar 2025 - Aug 2025",
    "Apr 2025 - Present",
    "May 2025 - Dec 2025",
    "Jul 2025 - Present",
    "Sep 2025 - Present",
    "Jan 2026 - Present",
    "Feb 2026 - Jun 2026",
    "Mar 2026 - Present"
]


job_bullets = [
    "Rebuilt authentication infrastructure using MongoDB, reducing user experience by 50%",
    "Developed scalable backend services using Kubernetes, improving system performance by 347%",
    "Implemented automated deployment pipelines using Docker, increasing deployment velocity by 823%",
    "Optimized database architecture using PostgreSQL, reducing query latency by 72%",
    "Migrated legacy systems to modern frameworks, improving reliability by 250%",
    "Designed API infrastructure using GraphQL, increasing developer productivity by 420%",
    "Built machine learning pipeline using Python, achieving 91% model accuracy",
    "Created distributed service architecture using AWS, reducing operational overhead by 63%",
    "Automated internal workflows using JavaScript, saving approximately 3000 engineering hours",
    "Improved application scalability through aggressive usage of microservices architecture by 500%",
    "Developed cloud infrastructure using Terraform, increasing deployment consistency by 88%",
    "Refactored critical backend systems, improving application stability by 97%",
    "Integrated AI-powered workflows, increasing team efficiency by 640%",
    "Built real-time processing systems handling millions of requests per second",
    "Optimized frontend rendering pipeline using React, improving load times by 45%",
    "Created monitoring infrastructure using Kubernetes, reducing production incidents by 70%",
    "Implemented security improvements across authentication systems, increasing platform trust by 900%",
    "Architected enterprise solutions using modern technologies, improving business impact by 312%",
    "Reduced technical debt by creating a folder specifically dedicated to technical debt",
    "Replaced manual processes with automated pipelines, increasing productivity by an undefined amount",
    "Introduced unnecessary abstraction layers, improving developer confusion by 200%",
    "Built a framework on top of another framework to solve framework limitations",
    "Implemented AI features after adding AI to the project description",
    "Improved engineering velocity through aggressive use of meetings",
    "Created production-ready infrastructure before creating the product",
    "Optimized code paths nobody used, achieving maximum theoretical performance",
    "Migrated entire platform while only breaking several minor features",
    "Enhanced system architecture through strategic buzzword alignment",
    "Improved application reliability by removing all unreliable code",
    "Developed scalable solutions capable of scaling further",
    "Put the fries in the bag"
]

projects = [
    "AI Resume Analyzer",
    "Personal Finance Dashboard",
    "Distributed Task Scheduler",
    "Real-Time Collaboration Platform",
    "Open Source Authentication Framework",
    "Machine Learning Recommendation Engine",
    "Cloud Deployment Manager",
    "Developer Productivity Toolkit",
    "Automated Code Review System",
    "Smart Inventory Management System",
    "AI-Powered Documentation Generator",
    "Personal Knowledge Management App",
    "Full Stack E-Commerce Platform",
    "Real-Time Chat Application",
    "Browser Automation Framework",
    "API Monitoring Dashboard",
    "Database Migration Tool",
    "Image Processing Pipeline",
    "Natural Language Processing Platform",
    "Portfolio Website",
    "Resume Slop Generator",
    "The World's Most Overengineered Todo App",
    "Enterprise Grade Calculator",
    "Blockchain Powered Weather Tracker",
    "AI Assistant That Writes Documentation",
    "Cloud Cost Optimization Platform",
    "Universal File Converter",
    "Automated Interview Preparation System",
    "Scalable URL Shortener",
    "The Framework That Builds Frameworks",
    "roblox game"
]


project_descriptions = [
    "Developed a full stack platform designed to solve complex workflow problems through modern software architecture",
    "Built an automated system for processing large amounts of data using scalable backend infrastructure",
    "Created a developer tool that improves productivity through intelligent automation and optimized workflows",
    "Designed a distributed application capable of handling high traffic workloads with minimal latency",
    "Engineered a cloud-based solution using modern technologies and production-ready architecture",
    "Created a machine learning system capable of analyzing patterns and generating useful predictions",
    "Built a platform that simplifies complicated technical processes through automation",
    "Developed a real-time application focused on performance, reliability, and user experience",
    "Implemented a complete software ecosystem demonstrating advanced engineering principles",
    "Designed and deployed an application using industry-standard technologies and best practices",
    "Created a highly scalable platform that solves a problem that may or may not have existed",
    "Built an intelligent assistant capable of automating repetitive developer workflows",
    "Developed a production-style application to explore distributed systems concepts",
    "Created a full stack project combining frontend interfaces with robust backend services",
    "Engineered a tool focused on improving developer experience and workflow efficiency",
    "Built an experimental platform exploring artificial intelligence and automation",
    "Designed a modern application architecture with unnecessary levels of scalability",
    "Created a project demonstrating advanced engineering concepts through practical implementation",
    "Developed an automated pipeline capable of reducing manual work through software solutions",
    "Built an application that started simple and eventually required Kubernetes",
    "Created a revolutionary platform that successfully solved the problem created by the platform",
    "Developed an enterprise-grade solution despite having approximately three users",
    "Built a scalable architecture prepared for millions of users currently not using the application",
    "Designed an AI-powered system after adding AI to the project requirements",
    "Created a complex infrastructure layer for a feature that required three lines of code",
    "Developed a comprehensive platform with more documentation than actual functionality",
    "Built a technically impressive application that mostly displays dashboards",
    "Created a system optimized for performance under completely unrealistic conditions",
    "Designed a modern software solution using every technology found in the tutorial",
    "Developed a framework intended to simplify development by introducing another framework",
    "Created a github repository where it just generates unrealistic resumes",
    "Made a scratch game"
]


project_bullets = [
    "Implemented scalable backend architecture using Node.js, improving application performance by 420%",
    "Designed responsive frontend interfaces using React, increasing user engagement by 300%",
    "Built automated deployment pipelines using Docker, reducing release time by 87%",
    "Integrated machine learning models using Python, achieving 94% prediction accuracy",
    "Created database optimization strategies using PostgreSQL, reducing query times by 65%",
    "Developed authentication systems using modern security practices, improving reliability by 250%",
    "Implemented cloud infrastructure using AWS, increasing scalability by 900%",
    "Designed REST APIs supporting thousands of requests while maintaining low latency",
    "Created automated testing workflows, reducing bugs discovered in production by 73%",
    "Built real-time communication features using WebSockets, improving response times by 60%",
    "Optimized application architecture through strategic refactoring, increasing maintainability by 180%",
    "Developed CI/CD pipelines that improved deployment efficiency by 500%",
    "Integrated third-party services and APIs, expanding platform capabilities by 340%",
    "Created monitoring systems that detected problems before users noticed them",
    "Implemented caching strategies using Redis, improving system speed by 76%",
    "Designed modular software components, reducing future development time by 90%",
    "Built scalable cloud services capable of supporting imaginary enterprise workloads",
    "Reduced application complexity by adding a carefully managed amount of complexity",
    "Created a database layer because using a spreadsheet was becoming too powerful",
    "Implemented authentication despite the project only having one account",
    "Optimized code that was already fast enough, achieving unnecessary performance gains",
    "Added AI functionality after discovering the word AI increased project credibility",
    "Created a complete architecture diagram larger than the actual application",
    "Implemented enterprise patterns for a personal project used exclusively by the developer",
    "Built a highly available system that was never deployed",
    "Reduced bugs by removing features nobody understood",
    "Improved user experience by adding more loading animations",
    "Developed a scalable solution ready for problems that do not exist yet",
    "Created documentation explaining the project better than the project itself",
    "Engineered a future-proof system that became outdated immediately"
]
